### ISSUE TITLE
SQL error on postgres for doesRevisionExist

### ISSUE THREAD

**Issue by rlivsey** [mwpastore/ember-cli-deploy-sql#2]
I get the following error when deploying:

```
|  +- sql
- Uploading `tmp/deploy-dist/index.html'
- error: select 1, "1" from "frontend_versions" where "key" = $1 limit $2 - column "1" does not exist
|
+- didFail
error: select 1, "1" from "frontend_versions" where "key" = $1 limit $2 - column "1" does not exist
error: column "1" does not exist
    at Connection.parseE (/Users/rlivsey/Development/ember-addons/ember-cli-deploy-sql/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/rlivsey/Development/ember-addons/ember-cli-deploy-sql/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/rlivsey/Development/ember-addons/ember-cli-deploy-sql/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
|
Pipeline aborted
```

This looks to be coming from [doesRevisionExist](https://github.com/mwpastore/ember-cli-deploy-sql/blob/f94a5e10065860ae7378b62cbebd4ca410947ed8/lib/deploy-client.js#L74-L79)

**Comment by mwpastore** [comment]
Thanks for the report! I think that fixes it, and I'll release it as beta.4 in a sec here.

**Comment by rlivsey** [comment]
Confirm all is working well with Postgres now 👍

**Comment by mwpastore** [comment]
Woohoo! 💥
